---
name: 'Check artifacts'
description: 'Check if an artifact exists.'
author: 'Thibault Cheneviere'

inputs:
  name:
    description: 'The name of the artifact to check.'
    required: true
  run_id:
    description: 'The run ID of the workflow that produced the artifact.'
    required: true
  token:
    description: 'The token to use to authenticate with the GitHub API.'
    required: true
  owner:
    description: 'The owner of the repository where the artifact is stored.'
    required: true
  repo:
    description: 'The repository where the artifact is stored.'
    required: true

outputs:
  artifact_exists:
    description: 'Whether the artifact exists.'

runs:
  using: 'node20'
  main: 'dist/index.js'
